### ISSUE TITLE
[B] Database cleanup

### ISSUE THREAD

**Issue by insaan21** [JID-2111/JID-2111#12]
As a user, I want to perform tests without modifying the original database so I can work without creating modifications. 

Acceptance Criteria: 
Scenario: A user performs a read operation. 
Given the user has connected to a database successfully; 
When the user performs a set of desired tests that read data; 
Then the application will read live data 
 
Scenario: The user chooses not to save resultant data from the operation. 
Given the user has connected to a database successfully; 
When the user performs a set of desired tests that add data; 
Then the application will delete any new data after completing tests. 
 
Scenario: A user performs a delete operation. 
Given the user has connected to a database successfully; 
When the user performs a set of desired tests that delete data; 
Then the application will write any data that was deleted after completing tests. 

- To handle deletes, look into shallow clones of a table

# Milestones
| Milestone                	| Date   	|
|--------------------------	|--------	|
| Determine  plan                     | Oct 30   |
| Rough implementation 	| Nov 4   	|
| Finalized                          	| Nov 6	|

**Comment by adityavidyadharan** [comment]
We will use SQL transactions to execute the stored procedures without affecting the data.

Transaction's can't be paused or rolled back later, so we will have to create a "query builder". It will create a large query which will first execute the procedure, then run all of our condition checks (multiple select commands). Each select's output is recorded by the `Pg` library and can be accessed individually to check conditions. At the end, we can just rollback the transaction.

```ts
const res = (await this.client.query(`
    BEGIN;

    select * from accounts where name = 'Alice';

    UPDATE accounts SET balance = balance - 100.00
        WHERE name = 'Alice';

    SAVEPOINT my_savepoint;

    UPDATE accounts SET balance = balance + 100.00
        WHERE name = 'Bob';
    -- oops ... forget that and use Wally's account
    ROLLBACK TO my_savepoint;

    select * from accounts where name = 'Alice';

    UPDATE accounts SET balance = balance + 100.00
        WHERE name = 'Wally';
    ROLLBACK;
`)) as unknown as any[];
    res
      .filter((r) => r.command === 'SELECT')
      .forEach((r) => console.log(r.rows));
    console.log(util.inspect(res[1], false, null, true));
```

**Comment by JackFratto** [comment]
Agreed, but we should have "BEGIN" and "ROLLBACK" be separate queries. This way a query doesn't get committed accidentally and we can rollback once the operation is complete or if the operation errors (i.e. inside of a finally block after try/catch) https://node-postgres.com/features/transactions

**Comment by insaan21** [comment]
> Agreed, but we should have "BEGIN" and "ROLLBACK" be separate queries. This way a query doesn't get committed accidentally and we can rollback once the operation is complete or if the operation errors (i.e. inside of a finally block after try/catch) https://node-postgres.com/features/transactions

Unfortunately, a trasactional block has to all be in one query, we can't pause the transaction in between if that makes sense

**Comment by adityavidyadharan** [comment]
> Agreed, but we should have "BEGIN" and "ROLLBACK" be separate queries. This way a query doesn't get committed accidentally and we can rollback once the operation is complete or if the operation errors (i.e. inside of a finally block after try/catch) https://node-postgres.com/features/transactions

I see what you mean but I don't think we should use this system because it's specific to the postgres library, and it may cause problems later with trying to integrate a new database provider which has a different node library
