### ISSUE TITLE
[B] Create functionality to detect rows by conditions

### ISSUE THREAD

**Issue by adityavidyadharan** [JID-2111/JID-2111#135]
Scenario: User specifies that the stored procedure should edit a record and change it to a certain value

This ticket will be purely to create the helper functions necessary for displaying the final results. Given parameters, return a list of matching rows.

Given a table, detect if a record does exist where attribute 

- Exactly matches value
- Contains value
- Does not contain value
- Has ID which exists in test data
- Has ID given by user

**Comment by insaan21** [comment]
@adityavidyadharan  this was fixed by #153 right?
