### ISSUE TITLE
[B] Apply test data to unit test

### ISSUE THREAD

**Issue by adityavidyadharan** [JID-2111/JID-2111#166]
Apply test data from a table to the unit test

Determine how it's done in Amod's sample doc

Apply it to our code

**Comment by adityavidyadharan** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/JID-2111-Unit-Testing-63069b4eb1f405001cf7868c/issues/JID-2111/JID-2111/166?planning-poker) with Zenhub @JackFratto

**Comment by JackFratto** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/JID-2111-Unit-Testing-63069b4eb1f405001cf7868c/issues/JID-2111/JID-2111/166?planning-poker) with Zenhub @adityavidyadharan
