### ISSUE TITLE
[F] Accept User Input

### ISSUE THREAD

**Issue by alex-hobby** [JID-2111/JID-2111#29]
As a user, I want to be able to input a list of columns and their values to be checked against the database.

AC:
- Have four input fields
  - Table to look in
  - Column to look at (can be search dropdown or input, implementation detail)
https://www.w3schools.com/howto/howto_js_filter_dropdown.asp
  - Condition to match by (contains, exactly, etc.)
  - Value to compare to
- Replaces "view code" area on Execute screen
For each rule in rule table,
- User can add additional column fields using a '+' button
- Each column field has a corresponding field to enter values

![Screen Shot 2022-09-23 at 3.00.23 PM.png](https://images.zenhubusercontent.com/63090e5f0e3775f60bd742c4/1e966ccb-05ce-44c8-82b5-192389a84197)

**Comment by insaan21** [comment]
This should be separated into separate tickets?
