### ISSUE TITLE
Write scripts for basic CRUD tests

### ISSUE THREAD

**Issue by alex-hobby** [JID-2111/JID-2111#30]
Write scripts to handle basic CRUD cases (Create, Read, Update, Delete).

Create: test if the proper tables are created
Read: test if the data is located within the database
Update: test if updating tables with certain values appears in the database
Delete: test if deleting values from tables appears in the database

As a User, I want to be able to verify whether certain records were created in my database.
As a User, I want to be able to verify whether certain records were updated within my database.
As a User, I want to be able to verify whether certain records were deleted within the database.

For this card, DO NOT need to worry about restoring the initial state of the database.

**Comment by insaan21** [comment]
Separating into multiple tickets
